minLength=8
requireUppercase=true
requireLowercase=true
requireDigit=true
requireSpecial=true
specialCharacters=!@\#$%^&*()_+-=[]{}|;:'\\\",.<>?/`~
weakPasswordScore=10
moderatePasswordScore=14
# score factor is how much the scores are incremented
scoreFactor=2
# comment to see if the sync is working